### ISSUE TITLE
About page to be added

### ISSUE THREAD

**Issue by parvathykrishnank** [parvathykrishnank/design4climate#12]

**Comment by mngbaloloy** [comment]
About page section here.
https://worldbankgroup-my.sharepoint.com.mcas.ms/:w:/g/personal/mbaloloy_worldbank_org/EfadXDkjOnREheuzhTsM6ZwBVLSJFgrZpSrJmZSFHpDtBg?CID=9ebf46c3-4f72-34c6-f415-9dc2e4f0f0ee

@parvathykrishnank can you also say something about the API/version? Maybe about 2-3 sentences?
