### ISSUE TITLE
Add notes for CCDR across pages

### ISSUE THREAD

**Issue by mngbaloloy** [parvathykrishnank/design4climate#14]
Add a note that "CCDR is a World Bank document and not a national strategy." There will be no 'adoption' year since it cannot be adopted, but rather we can add an asterisk/note that the year being shown on the Dashboard refers to the document/publication year.

**Comment by parvathykrishnank** [comment]
<img width="1497" alt="image" src="https://github.com/user-attachments/assets/fa6915f1-251a-4c7e-89f7-263c48afcea9">


Updated note for CCDR
