### ISSUE TITLE
Update about section

### ISSUE THREAD

**Issue by mngbaloloy** [parvathykrishnank/design4climate#19]
Sasa made some edits on the About section description. Kindly update with this document: 
https://worldbankgroup-my.sharepoint.com/:w:/r/personal/mbaloloy_worldbank_org/Documents/CLAD-ECA%20About%20Page.docx?d=w395c9df63a23447485ebb3853b0ce99c&csf=1&web=1&e=YAaKNt

**Comment by parvathykrishnank** [comment]
Updated on Aug 21st.
