### ISSUE TITLE
Column M - Policy Type 2 was newly added

### ISSUE THREAD

**Issue by parvathykrishnank** [parvathykrishnank/design4climate#5]
For the tags, to include the specific language available in Column J - Language_2 for all Non-English documents. Also, Column M - Policy Type 2 was newly added. FYI, I have also changed CCDR to "Others" for Policy Type, and "World Bank Report" for Policy Type 2.

**Comment by parvathykrishnank** [comment]
@mngbaloloy do we need to add both Policy Type 1 and Policy Type 2 on the dashboard?

**Comment by mngbaloloy** [comment]
@parvathykrishnank no need to add it on the dashboard but it would be useful to add it on the View Database as an additional tag under "Status, Language, and Accessibility". For example, Albania's Climate Change Strategy includes both the 'strategy' and the 'action plan' so it's policy type is "National Strategy/Program" but with an additional tag of "Action Plan". So when people search for "action plan", it shows based on both the Policy Type and Policy Type 2 columns. Feel free to rename if you think there's a better way to present it.

**Comment by parvathykrishnank** [comment]
Removed column Policy Type
